PythonVersion="3.12.11"
pythonBuildCommandsFile="/tmp/zipdeploy/extracted/oryx-build-commands.txt"
packagedir=".python_packages/lib/site-packages"
OperationId="5145583de134ab75"
SourceDirectoryInBuildContainer="/tmp/zipdeploy/extracted"
PlatformName="python"
CompressDestinationDir="false"
